### ISSUE TITLE
Must be a two-dimensional array (one for the x-value and one for the y-value)

### ISSUE THREAD

**Issue by NadineSteinbach** [edmundlehsten/Newton_fractals#11]
https://github.com/edmundlehsten/Newton_fractals/blob/4af8125a9a20d34e0ba628a7caf9c8793d3165b7/Main.py#L19

**Comment by edmundlehsten** [comment]
Fixed by making a minor change:
### from:
https://github.com/edmundlehsten/Newton_fractals/blob/5e050a34ca30eaa7703b9be4ac932f5db82f6eb8/Main.py#L19
### to:
https://github.com/edmundlehsten/Newton_fractals/blob/02db9c32ca64ef8a14e55eee965bb62e4e11f726/Main.py#L19
