### ISSUE TITLE
Must also be altered because of each zero-vector being two-dimensional

### ISSUE THREAD

**Issue by NadineSteinbach** [edmundlehsten/Newton_fractals#12]
https://github.com/edmundlehsten/Newton_fractals/blob/4af8125a9a20d34e0ba628a7caf9c8793d3165b7/Main.py#L42

**Comment by edmundlehsten** [comment]
I think I fixed the error, have a look at the get zeros method in branch (issue 12)
### This is the new Mehtod
https://github.com/edmundlehsten/Newton_fractals/blob/4059af6b51426ee29eef7c17aa45982810a3a6fc/Main.py#L42-L62

### These are the lines that have actually changed:
https://github.com/edmundlehsten/Newton_fractals/blob/4059af6b51426ee29eef7c17aa45982810a3a6fc/Main.py#L58-L59
