### ISSUE TITLE
Test if ndarray directly instead

### ISSUE THREAD

**Issue by edmundlehsten** [edmundlehsten/Newton_fractals#15]
https://github.com/edmundlehsten/Newton_fractals/blob/13e6aeba5ffde66b2932c577cdc71ffa33fc774d/Main.py#L30
it takes time to convert something to a string and check if two strings are equal, instead you can check the way you did here:
https://github.com/edmundlehsten/Newton_fractals/blob/13e6aeba5ffde66b2932c577cdc71ffa33fc774d/Main.py#L28
a numpy array in this case would be referenced with np.ndarray hence you could just change it to:

`if isinstance(guess,(list,tuple,np.ndarray)) and `size(guess)==2:`

and then you can change this to only else:
https://github.com/edmundlehsten/Newton_fractals/blob/13e6aeba5ffde66b2932c577cdc71ffa33fc774d/Main.py#L30

**Comment by NadineSteinbach** [comment]
Thank you for your help. I have tried to find something like this but I have not found it.
