### ISSUE TITLE
Task 6

### ISSUE THREAD

**Issue by NadineSteinbach** [edmundlehsten/Newton_fractals#16]

**Comment by edmundlehsten** [comment]
there is no need to do this:
https://github.com/edmundlehsten/Newton_fractals/blob/95542ad0f74c064d46ed5dda296a35802b93e38f/Main.py#L11

it will just slow down all following computations using this as string objects are big and compairisons on them take a long time so if we check if it is equal to the string None then it will be slower than it we set it equal to None in which case checking if it is None will be quicker,
also here you could set it equal to partialDerivatives directly as methods are objects hence we can say that the method is the method accurate method we get from the user or it will be the approximated method,
### i.e.
replace 
https://github.com/edmundlehsten/Newton_fractals/blob/95542ad0f74c064d46ed5dda296a35802b93e38f/Main.py#L11
with
`self.derivativeInput = partialDerivatives`

**Comment by NadineSteinbach** [comment]
I cannot write the last line because partialDerivatives comes after __init__ and therefor does it not yet know what it is. But we could write the function partialDerivatives in __init__. Does that help?

**Comment by edmundlehsten** [comment]
that would work, though you could probably just place it before the init function right after the class declaration as python is a scripted language it will read that first before the init and then know about it.

**Comment by NadineSteinbach** [comment]
The problem is that I need (f,x,y) as an input. I tried to do it without (x,y) but that does not work. So I prefer to leave it as I had it in the beginning: an extra method underneath __init__ (just without the string part).

**Comment by edmundlehsten** [comment]
For a performance increase it would still be best to change this line:
https://github.com/edmundlehsten/Newton_fractals/blob/95542ad0f74c064d46ed5dda296a35802b93e38f/Main.py#L11
to:
`self.derivativeInput=None `

and then change 
https://github.com/edmundlehsten/Newton_fractals/blob/95542ad0f74c064d46ed5dda296a35802b93e38f/Main.py#L30
to `if self.derivativeInput==None: `

This will be quicker because testing if an object is of type None is quicker than testing if two strings are the same

**Comment by edmundlehsten** [comment]
I dont see what you mean in your previous comment though, for example:
```python
class a:
    def k(self,a,b):
        return self.h
    def __init__(self,a,b):
        self.h = a
```
if you now call the following:
```python
p = a(1,3)
p.k(2,3) #will return 1
```

similarly you could adjust the class as follows:
```python
class fractal2D:
    def partialDerivatives(self,x,y):
        f = self.function
        J=np.zeros(2)
        h=1e-10
        J=1/h*array([f(x+h,y)-f(x,y),f(x,y+h)-f(x,y)]).T
        return J

    def __init__(self, f, derivative = None):
        # method description (did not bother to copy it :) )
        self.function = f
        self.zeros = np.array([[]])
        if derivative == None:
            self.derivative = partialDerivatives(self, x, y)
        else:
            self.derivative = derivative
```
then whenever we need to get the derivative within the class all we need to do is call `self.derivative(x,y)`
