### ISSUE TITLE
Why did you put a minus there and not a plus?

### ISSUE THREAD

**Issue by NadineSteinbach** [edmundlehsten/Newton_fractals#22]
https://github.com/edmundlehsten/Newton_fractals/blob/4059af6b51426ee29eef7c17aa45982810a3a6fc/Main.py#L58

**Comment by edmundlehsten** [comment]
it was supposed to be a plus thanks for spotting that mistake...
the line after it gives the index at which point the zero was, what i forgot to write was the `return` in front of it, went ahead an implemented the changes, now it looks like this:
https://github.com/edmundlehsten/Newton_fractals/blob/d50cd508ef20bf2335381f335a7fc578fd890bcd/Main.py#L58-L61
